### ISSUE TITLE
Глаз мозолят

### ISSUE THREAD

**Issue by ferrovovan** [VadimAndreich/Signals#1]
![Снимок экрана от 2024-11-17 19-44-43](https://github.com/user-attachments/assets/036f6430-5461-4931-ba1c-3b4f0019a8c2)  

Выключи, пожалуйста.

**Comment by VadimAndreich** [comment]
Не выключу.

**Comment by ferrovovan** [comment]
Добавь `README.md`:
```
Signals tasks
```
